### ISSUE TITLE
Read Sms not works

### ISSUE THREAD

**Issue by DaneelReventelov** [AChep/AcDisplay#102]
No problem on notification and I can read correctly the preview but when I click on "read" the app not brings me to sms app, it simply delete the notification.
Smartphone: Meizu M2 note
SMS app: standard one
Thanks

**Comment by AChep** [comment]
Uhm, is it `Read` not in `Mark as read` meaning?

**Comment by DaneelReventelov** [comment]
"Read"
When you tap on notification icon and AcDisplay show you the sms preview, there are 3 options, "Read", "Filter" and "Delete". If I swipe on sender Name, Acdisplay opens the sms app but if I click on "Read" don't works.

**Comment by DaneelReventelov** [comment]
Mumble! A doubt came in my mind, I wrote that there are 3 options "Read", "Filter" and "Delete" but I translate from my language (Italian). In AcDisplay I have "Leggi" that can be translated "go to read" and literally "read" but maybe "read" was used as past verb to say "mark as read" and in Italian is "Letto"
- Read (present) = "Go to read" = "Leggi"
- Read (past) = "Mark as read" = "Letto"
So this bug can also be a simple translation error, let me know

**Comment by CarlosACepeda** [comment]
Well, notification texts are from the App's owner(s) so any translation error in any notification is out of AcDisplay's scope, 🤔  btw, prob the text was 'Mark as read'.
Can you send screenshots, please? 
I will close the issue as stale, but if you think it is still a problem, please comment some screenshots because with text is kind of hard to know such things, 😄
