### ISSUE TITLE
Use clock along with custom widget on AcDisplay lockscreen?

### ISSUE THREAD

**Issue by sdbbs** [AChep/AcDisplay#163]
I'm using the version of AcDisplay from f-droid (turns out, it is last updated 2015-08-02, so maybe this has been fixed since), as a lock screen replacement for recent LineageOS (I believe it corresponds to Android 9).

All I want is a lock screen that will show me clock, - and a widget from a notes application, that I can touch and open from the lockscreen.

By default, AcDisplay shows a clock - which is great.

However, once I add the notes widget (which is touchable and opens the application - which is great), the clock disappears from AcDisplay lock screen. Then I thought, I'd just add a clock widget in addition - but it turns out, in this version, you can only add one widget to the lockscreen, so I cannot add both a clock and a notes widget to the AcDisplay lockscreen.

Is there a way to add both a clock and a (touchable) notes widget to the AcDisplay lockscreen?

**Comment by CarlosACepeda** [comment]
It hasn't been fixed, yes, you're right 😄 
Currently there's not a way to do so, I am currently making some maintenance to the app, so maybe I will take it into consideration, but it'll be more of a 'no' than a 'yes' because I am not entirely familiar with the app and I am focused on updating it to be usable on newer Android versions and fixing some of the issues, :))
