### ISSUE TITLE
Bug with HoverChat

### ISSUE THREAD

**Issue by Ack0** [AChep/AcDisplay#80]
When I click on **HoverChat**'s bubble the **AcDisplay** tries to "steal"
the focus and HoverChat too. The result is this:
http://i304.photobucket.com/albums/nn191/xkvr/AcDisplay/HoverChat_zpsacjvxx4w.gif
I tried with **Textra**, and everything works fine.

Moto G XT1069 Android 5.0.2

**Comment by CarlosACepeda** [comment]
It all depends on the other app, not AcDisplay.
As you said, focus.
The other app is trying to gain focus over AcDisplay and AcDisplay does the same,
however, in order to avoid this the other app must spawn their floating views as Non-focusable views.
And AcDisplay can't know which app is taking focus now, only knows is has lost it and tries to go fullscreen when that happens.
